### ISSUE TITLE
ερώτηση

### ISSUE THREAD

**Issue by team7ml** [Deffro/random-dose-of-knowledge#2]
Το έχεις κανει  deploy στο  aws? δεν κοστίζει αυτο?

**Comment by Deffro** [comment]
I am translating the text for future readers.

Title: "Question"

Body: "Have you deployed it on AWS. Doesn't it cost?"

Yes, you can read the blog post I wrote about the procedure of the project for more information! AWS offers a free EC2 instance with 1 CPU core and 1GB of RAM.
